name: numbers
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  flame: ^1.0.0-rc10
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  shared_preferences: ^2.0.6
  soundpool: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # generate: true
  uses-material-design: true

  assets:
    - assets/images/
  #   - texts/
  #   - anims/
    - assets/sounds/

  fonts:
    - family: quicksand
      fonts:
        - asset: fonts/quicksand-bold.ttf