name: numbers
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.9+10

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  appsflyer_sdk: ^6.2.4+4-nullsafety
  cupertino_icons: ^1.0.3
  device_info: ^2.0.2
  flame: ^1.0.0-rc13
  flame_svg: ^1.0.0-rc3
  firebase_analytics: ^8.2.0
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.4
  flutter_local_notifications: ^6.0.0
  flutter_svg: ^0.22.0
  games_services: ^2.0.0-nullsafety.3
  in_app_purchase: ^1.0.6
  intl: ^0.17.0
  path_provider: ^2.0.2
  screenshot: ^1.2.3
  share: ^2.0.4
  shared_preferences: ^2.0.6
  smartlook: ^2.0.1
  soundpool: ^2.1.0
  rive: ^0.7.22
  unity_ads_plugin: ^0.2.2
  vibration: ^1.7.4-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # generate: true
  uses-material-design: true

  assets:
    - anims/
    - assets/images/
  #   - texts/
    - assets/sounds/

  fonts:
    - family: quicksand
      fonts:
        - asset: fonts/quicksand-bold.ttf
    - family: icons
      fonts:
        - asset: fonts/myicons.ttf