name: numbers
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.30+30

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  admob_flutter: ^2.0.0-nullsafety.1
  appsflyer_sdk: ^6.4.0+1
  confetti: ^0.6.0
  cupertino_icons: ^1.0.3
  device_info: ^2.0.2
  flame: 1.0.0-releasecandidate.12
  flame_svg: 1.0.0-rc4
  firebase_analytics: ^8.2.0
  firebase_core: ^1.4.0
  firebase_messaging: ^11.1.0
  flutter_rating_bar: ^4.0.0
  flutter_svg: 0.22.0
  games_services: ^2.0.1
  gameanalytics_sdk: ^1.0.6
  http: ^0.13.4
  in_app_purchase: ^1.0.6
  in_app_review: ^2.0.2
  install_prompt: ^0.0.1
  intl: ^0.17.0
  package_info_plus: ^1.0.6
  shared_preferences: ^2.0.6
  soundpool: ^2.1.0
  rive: ^0.7.33
  unity_ads_plugin: ^0.2.2
  url_launcher: ^6.0.12
  vibration: ^1.7.4-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # generate: true
  uses-material-design: true

  assets:
    - anims/
    - assets/images/
    - assets/sounds/
    - texts/

  fonts:
    - family: quicksand
      fonts:
        - asset: fonts/quicksand-bold.ttf
    - family: icons
      fonts:
        - asset: fonts/myicons.ttf